// Code generated by runtime_manifest_v2.py; DO NOT EDIT.
package loadstrike

func init() {
	if runtimePublisherTrustedKeysJSON != "" {
		panic("runtime publisher keyring configured more than once")
	}
	runtimePublisherTrustedKeysJSON = "[{\"activation\":1785149337,\"algorithm\":\"publisher-ed25519-v2\",\"keyId\":\"sha256:1c64a76910dc2a99d104f3153ab2d2ae7cffd9fce178cea60184b38e2e4de97c\",\"notAfter\":1879757637,\"publicKeyRawBase64\":\"c6tDE5Y/lU6a7NwaBma6VghDtn6Zz429Qn5vqKnzUUc=\"}]"
}
