// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: runtimeproto/loadstrike_runtime.proto

package runtimeproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostRuntime_Handshake_FullMethodName  = "/runtimeproto.HostRuntime/Handshake"
	HostRuntime_InvokeStep_FullMethodName = "/runtimeproto.HostRuntime/InvokeStep"
)

// HostRuntimeClient is the client API for HostRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostRuntimeClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	InvokeStep(ctx context.Context, in *InvokeStepRequest, opts ...grpc.CallOption) (*InvokeStepResponse, error)
}

type hostRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewHostRuntimeClient(cc grpc.ClientConnInterface) HostRuntimeClient {
	return &hostRuntimeClient{cc}
}

func (c *hostRuntimeClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, HostRuntime_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostRuntimeClient) InvokeStep(ctx context.Context, in *InvokeStepRequest, opts ...grpc.CallOption) (*InvokeStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeStepResponse)
	err := c.cc.Invoke(ctx, HostRuntime_InvokeStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostRuntimeServer is the server API for HostRuntime service.
// All implementations must embed UnimplementedHostRuntimeServer
// for forward compatibility.
type HostRuntimeServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	InvokeStep(context.Context, *InvokeStepRequest) (*InvokeStepResponse, error)
	mustEmbedUnimplementedHostRuntimeServer()
}

// UnimplementedHostRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostRuntimeServer struct{}

func (UnimplementedHostRuntimeServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedHostRuntimeServer) InvokeStep(context.Context, *InvokeStepRequest) (*InvokeStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeStep not implemented")
}
func (UnimplementedHostRuntimeServer) mustEmbedUnimplementedHostRuntimeServer() {}
func (UnimplementedHostRuntimeServer) testEmbeddedByValue()                     {}

// UnsafeHostRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostRuntimeServer will
// result in compilation errors.
type UnsafeHostRuntimeServer interface {
	mustEmbedUnimplementedHostRuntimeServer()
}

func RegisterHostRuntimeServer(s grpc.ServiceRegistrar, srv HostRuntimeServer) {
	// If the following call panics, it indicates UnimplementedHostRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostRuntime_ServiceDesc, srv)
}

func _HostRuntime_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostRuntimeServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostRuntime_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostRuntimeServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostRuntime_InvokeStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostRuntimeServer).InvokeStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostRuntime_InvokeStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostRuntimeServer).InvokeStep(ctx, req.(*InvokeStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostRuntime_ServiceDesc is the grpc.ServiceDesc for HostRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtimeproto.HostRuntime",
	HandlerType: (*HostRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _HostRuntime_Handshake_Handler,
		},
		{
			MethodName: "InvokeStep",
			Handler:    _HostRuntime_InvokeStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtimeproto/loadstrike_runtime.proto",
}
