// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: runtimeproto/loadstrike_runtime.proto

package runtimeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SdkVersion      string                 `protobuf:"bytes,1,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_runtimeproto_loadstrike_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HandshakeRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SdkVersion      string                 `protobuf:"bytes,1,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_runtimeproto_loadstrike_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HandshakeResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type InvokeStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallbackId    string                 `protobuf:"bytes,1,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	ScenarioName  string                 `protobuf:"bytes,2,opt,name=scenario_name,json=scenarioName,proto3" json:"scenario_name,omitempty"`
	StepName      string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStepRequest) Reset() {
	*x = InvokeStepRequest{}
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStepRequest) ProtoMessage() {}

func (x *InvokeStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStepRequest.ProtoReflect.Descriptor instead.
func (*InvokeStepRequest) Descriptor() ([]byte, []int) {
	return file_runtimeproto_loadstrike_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeStepRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

func (x *InvokeStepRequest) GetScenarioName() string {
	if x != nil {
		return x.ScenarioName
	}
	return ""
}

func (x *InvokeStepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

type InvokeStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStepResponse) Reset() {
	*x = InvokeStepResponse{}
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStepResponse) ProtoMessage() {}

func (x *InvokeStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtimeproto_loadstrike_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStepResponse.ProtoReflect.Descriptor instead.
func (*InvokeStepResponse) Descriptor() ([]byte, []int) {
	return file_runtimeproto_loadstrike_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeStepResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *InvokeStepResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *InvokeStepResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_runtimeproto_loadstrike_runtime_proto protoreflect.FileDescriptor

const file_runtimeproto_loadstrike_runtime_proto_rawDesc = "" +
	"\n" +
	"%runtimeproto/loadstrike_runtime.proto\x12\fruntimeproto\"^\n" +
	"\x10HandshakeRequest\x12\x1f\n" +
	"\vsdk_version\x18\x01 \x01(\tR\n" +
	"sdkVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\"_\n" +
	"\x11HandshakeResponse\x12\x1f\n" +
	"\vsdk_version\x18\x01 \x01(\tR\n" +
	"sdkVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\x05R\x0fprotocolVersion\"v\n" +
	"\x11InvokeStepRequest\x12\x1f\n" +
	"\vcallback_id\x18\x01 \x01(\tR\n" +
	"callbackId\x12#\n" +
	"\rscenario_name\x18\x02 \x01(\tR\fscenarioName\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\"n\n" +
	"\x12InvokeStepResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xac\x01\n" +
	"\vHostRuntime\x12L\n" +
	"\tHandshake\x12\x1e.runtimeproto.HandshakeRequest\x1a\x1f.runtimeproto.HandshakeResponse\x12O\n" +
	"\n" +
	"InvokeStep\x12\x1f.runtimeproto.InvokeStepRequest\x1a .runtimeproto.InvokeStepResponseB$Z\"loadstrike.com/sdk/go/runtimeprotob\x06proto3"

var (
	file_runtimeproto_loadstrike_runtime_proto_rawDescOnce sync.Once
	file_runtimeproto_loadstrike_runtime_proto_rawDescData []byte
)

func file_runtimeproto_loadstrike_runtime_proto_rawDescGZIP() []byte {
	file_runtimeproto_loadstrike_runtime_proto_rawDescOnce.Do(func() {
		file_runtimeproto_loadstrike_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtimeproto_loadstrike_runtime_proto_rawDesc), len(file_runtimeproto_loadstrike_runtime_proto_rawDesc)))
	})
	return file_runtimeproto_loadstrike_runtime_proto_rawDescData
}

var file_runtimeproto_loadstrike_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_runtimeproto_loadstrike_runtime_proto_goTypes = []any{
	(*HandshakeRequest)(nil),   // 0: runtimeproto.HandshakeRequest
	(*HandshakeResponse)(nil),  // 1: runtimeproto.HandshakeResponse
	(*InvokeStepRequest)(nil),  // 2: runtimeproto.InvokeStepRequest
	(*InvokeStepResponse)(nil), // 3: runtimeproto.InvokeStepResponse
}
var file_runtimeproto_loadstrike_runtime_proto_depIdxs = []int32{
	0, // 0: runtimeproto.HostRuntime.Handshake:input_type -> runtimeproto.HandshakeRequest
	2, // 1: runtimeproto.HostRuntime.InvokeStep:input_type -> runtimeproto.InvokeStepRequest
	1, // 2: runtimeproto.HostRuntime.Handshake:output_type -> runtimeproto.HandshakeResponse
	3, // 3: runtimeproto.HostRuntime.InvokeStep:output_type -> runtimeproto.InvokeStepResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtimeproto_loadstrike_runtime_proto_init() }
func file_runtimeproto_loadstrike_runtime_proto_init() {
	if File_runtimeproto_loadstrike_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtimeproto_loadstrike_runtime_proto_rawDesc), len(file_runtimeproto_loadstrike_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtimeproto_loadstrike_runtime_proto_goTypes,
		DependencyIndexes: file_runtimeproto_loadstrike_runtime_proto_depIdxs,
		MessageInfos:      file_runtimeproto_loadstrike_runtime_proto_msgTypes,
	}.Build()
	File_runtimeproto_loadstrike_runtime_proto = out.File
	file_runtimeproto_loadstrike_runtime_proto_goTypes = nil
	file_runtimeproto_loadstrike_runtime_proto_depIdxs = nil
}
